[package]
name = "nethsm-backup"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
clap = { version = "4.5.20", features = ["derive"], optional = true }
scrypt = "0.11.0"
testresult = "0.4.1"

[features]
cli = ["dep:clap"]

[[bin]]
name = "main"
required-features = ["cli"]
